name: .NET

on:
  push:
    branches:
      - main
      - DOT-28-nuget-pack
  pull_request:
    branches:
      - main
      - DOT-28-nuget-pack

env:
  NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API }}
  VERSION_STATIC: 1.0.0  # Specify the desired static version here

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ['csharp']

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        source-url: https://api.nuget.org/v3/index.json
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and publish
      run: |
        mkdir __out
        for project in src/ITL.DataAccess/*.csproj src/ITL.Executor/*.csproj src/ITL.Extensions/*.csproj src/ITL.Impl.Dapper.PostgreSql/*.csproj src/ITL.Impl.Dapper/*.csproj src/ITL.Impl.EF/*.csproj src/ITL.Impl.ElasticSearch/*.csproj src/ITL.Impl.Kafka/*.csproj src/ITL.Impl.Memory/*.csproj src/ITL.Impl.MongoDB/*.csproj src/ITL.Impl.Prometheus/*.csproj src/ITL.Impl.Rabbit/*.csproj src/ITL.Templ.WebApi/*.csproj src/ITL.Web/*.csproj; do
          dotnet pack --no-restore -o __out -p:Version=$VERSION_STATIC $project
        done
        dotnet nuget push "__out/*.nupkg" --skip-duplicate --no-symbols --api-key ${{secrets.NUGET_API}}
