name: .NET

on:
  push:
    branches:
      - main
      - DOT-28-nuget-pack
      - dotnet-test
  pull_request:
    branches:
      - main
      - DOT-28-nuget-pack
      - dotnet-test

env:
  NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API }}
  # VERSION_STATIC: 1.0.${{ github.run_number }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ['csharp']

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        source-url: https://api.nuget.org/v3/index.json
        dotnet-version: 6.0.x

    # - name: Restore dependencies
    #   run: dotnet restore
    #   run: dotnet restore

    - name: Build and publish
      run: |
        mkdir __out
        for project in src/**/*.csproj; do
          version=$(date -u +"%y.%m.%d").${{ github.run_number }}
          dotnet pack --no-restore -o __out -p:Version=$version $project
        done
        dotnet nuget push "__out/*.nupkg" --skip-duplicate --no-symbols --api-key ${{secrets.NUGET_API}}


